---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: mlops-flux-system
  path: ./bitnami-postgres/16.2.0
  prune: true
  wait: true
  timeout: 10m0s